# Generated by Django 5.2.12 on 2026-04-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
